#!/usr/bin/sh
################################################################################
# Automatic Brightness Control (abc)
# File name : abc.sh
# Author : Masroor Rasheed
# email : masroor.rasheed@gmail.com
################################################################################
#
# Files that are utilized in this process.
DISPLAY_FILE="/sys/class/backlight/intel_backlight/brightness"
KEYBOARD_FILE="/sys/class/leds/smc::kbd_backlight/brightness"
LIGHT_FILE="/sys/devices/platform/applesmc.768/light"

# Determine the light intensity around the laptop
LIGHT=$(cat  ${LIGHT_FILE} | tr -d '()' | awk -F, '{print $1}' )

# Maximum and Current Display Brightness
CUR_DB=$(< /sys/class/backlight/intel_backlight/brightness)
MAX_DB=$(< /sys/class/backlight/intel_backlight/max_brightness)

# Maximum and Current Back light for keyboard
CUR_KB=$(< /sys/class/leds/smc::kbd_backlight/brightness)
MAX_KB=$(( $(< /sys/class/leds/smc::kbd_backlight/max_brightness) -55 ))

# Setting the new value based on configuration file
NEW_KB=$(( ${MAX_KB} - ($LIGHT * 75) ))
NEW_DB=$(( ($LIGHT * 50) + 200 ))

# Ensuring negative values for Keyboard brightness are not sent to file.
if [ ${NEW_KB} -lt 0 ]; then
	NEW_KB=0
fi
# Ensuring the brightness is not greater than the capabilities of hardware.
if [ ${NEW_DB} -gt ${MAX_DB} ]; then
	NEW_DB=${MAX_DB}
fi

# Printing out the information of the operations
echo "Outside Light is ${LIGHT}"
echo "Display Brightness ${CUR_DB} --> ${NEW_DB} : ${MAX_DB}"
echo "Keyboard Light is ${CUR_KB} --> ${NEW_KB} : ${MAX_KB}"

# Writing the settings to system files for changes
sudo sh -c "echo ${NEW_DB} > ${DISPLAY_FILE}"
sudo sh -c "echo ${NEW_KB} > ${KEYBOARD_FILE}" 
